dist: trusty
language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean site -Psite --errors --batch-mode
  - mvn clean install -Pqulice --errors --batch-mode
install:
  - gem install pdd -v 0.20.5
  - gem install est -v 0.3.4
  - gem install xcop -v 0.6
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
